CREATE TABLE public.alert_configurations (
    countdown_duration_seconds integer NOT NULL,
    user_id uuid NOT NULL,
    message_template character varying(4000) NOT NULL
);
CREATE TABLE public.alert_dispatch_attempts (
    success boolean NOT NULL,
    attempted_at timestamp(6) with time zone NOT NULL,
    contact_id bigint,
    id bigint NOT NULL,
    recording_id uuid,
    error_message character varying(2000)
);
ALTER TABLE public.alert_dispatch_attempts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.alert_dispatch_attempts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.devices (
    created_at timestamp(6) with time zone NOT NULL,
    last_seen_at timestamp(6) with time zone NOT NULL,
    revoked_at timestamp(6) with time zone,
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    name character varying(255) NOT NULL,
    token_hash character varying(255) NOT NULL
);
CREATE TABLE public.emergency_contacts (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    message_override character varying(2000),
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL
);
ALTER TABLE public.emergency_contacts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.emergency_contacts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.metadata_samples (
    latitude numeric(9,6),
    longitude numeric(9,6),
    client_timestamp timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    server_received_at timestamp(6) with time zone NOT NULL,
    recording_id uuid NOT NULL,
    device_info character varying(255)
);
ALTER TABLE public.metadata_samples ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.metadata_samples_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.recording_segments (
    segment_number integer NOT NULL,
    uploaded boolean NOT NULL,
    end_time timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    size_bytes bigint NOT NULL,
    start_time timestamp(6) with time zone NOT NULL,
    recording_id uuid NOT NULL,
    file_path character varying(512) NOT NULL
);
ALTER TABLE public.recording_segments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recording_segments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.recordings (
    alerts_dispatched_at timestamp(6) with time zone,
    countdown_ends_at timestamp(6) with time zone,
    ended_at timestamp(6) with time zone,
    started_at timestamp(6) with time zone NOT NULL,
    id uuid NOT NULL,
    status character varying(16) NOT NULL,
    user_id uuid NOT NULL,
    view_secret character varying(255) NOT NULL
);
CREATE TABLE public.sessions (
    expires_at timestamp(6) with time zone NOT NULL,
    issued_at timestamp(6) with time zone NOT NULL,
    last_used_at timestamp(6) with time zone NOT NULL,
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    label character varying(255) NOT NULL,
    previous_token_hash character varying(255),
    refresh_token_hash character varying(255) NOT NULL
);
CREATE TABLE public.users (
    verified boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id uuid NOT NULL,
    email character varying(255) NOT NULL,
    fullname character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL
);
CREATE TABLE public.verification_codes (
    attempts integer NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    last_sent_at timestamp(6) with time zone NOT NULL,
    user_id uuid NOT NULL,
    code_hash character varying(255) NOT NULL,
    purpose character varying(255) NOT NULL
);
ALTER TABLE ONLY public.alert_configurations
    ADD CONSTRAINT alert_configurations_pkey PRIMARY KEY (user_id);
ALTER TABLE ONLY public.alert_dispatch_attempts
    ADD CONSTRAINT alert_dispatch_attempts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.devices
    ADD CONSTRAINT devices_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.devices
    ADD CONSTRAINT devices_token_hash_key UNIQUE (token_hash);
ALTER TABLE ONLY public.emergency_contacts
    ADD CONSTRAINT emergency_contacts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.emergency_contacts
    ADD CONSTRAINT emergency_contacts_user_id_email_key UNIQUE (user_id, email);
ALTER TABLE ONLY public.metadata_samples
    ADD CONSTRAINT metadata_samples_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.recording_segments
    ADD CONSTRAINT recording_segments_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.recording_segments
    ADD CONSTRAINT recording_segments_recording_id_segment_number_key UNIQUE (recording_id, segment_number);
ALTER TABLE ONLY public.recordings
    ADD CONSTRAINT recordings_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.recordings
    ADD CONSTRAINT recordings_view_secret_key UNIQUE (view_secret);
ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_refresh_token_hash_key UNIQUE (refresh_token_hash);
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.verification_codes
    ADD CONSTRAINT verification_codes_pkey PRIMARY KEY (user_id, purpose);
CREATE INDEX idx_metadata_recording_time ON public.metadata_samples USING btree (recording_id, client_timestamp);
CREATE INDEX idx_recordings_countdown ON public.recordings USING btree (countdown_ends_at);
CREATE INDEX idx_recordings_user_status ON public.recordings USING btree (user_id, status);
